name = "aether"
compatibility_date = "2026-07-08"
[[kv_namespaces]]
binding = "CACHE"
id = "c42f0eafddf1441989bd28e1d29a0f09"

[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
enabled = true
invocation_logs = true
persist = true

[observability.traces]
enabled = true
persist = true
head_sampling_rate = 1
